---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Zabbix repository key
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Install Zabbix repository
  apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/6.0/ubuntu jammy main"
    state: present
    filename: zabbix

- name: Install Zabbix agent
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix agent
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
  notify: restart zabbix-agent

- name: Enable and start Zabbix agent
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started
